/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef u_int rpc_uint;
#ifdef __cplusplus
extern "C" bool_t xdr_rpc_uint(XDR *, rpc_uint*);
#elif __STDC__
extern  bool_t xdr_rpc_uint(XDR *, rpc_uint*);
#else /* Old Style C */
bool_t xdr_rpc_uint();
#endif /* Old Style C */

#define MAX_FILENAME_LENGTH 128
#define MAX_FILES 50
#define MAX_PATH_LENGTH 4096

struct request {
	char *filename;
	u_int size;
	u_int src_offset;
	u_int dest_offset;
};
typedef struct request request;
#ifdef __cplusplus
extern "C" bool_t xdr_request(XDR *, request*);
#elif __STDC__
extern  bool_t xdr_request(XDR *, request*);
#else /* Old Style C */
bool_t xdr_request();
#endif /* Old Style C */


struct chunk {
	char *filename;
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int size;
	u_int dest_offset;
};
typedef struct chunk chunk;
#ifdef __cplusplus
extern "C" bool_t xdr_chunk(XDR *, chunk*);
#elif __STDC__
extern  bool_t xdr_chunk(XDR *, chunk*);
#else /* Old Style C */
bool_t xdr_chunk();
#endif /* Old Style C */


typedef char *filename_t;
#ifdef __cplusplus
extern "C" bool_t xdr_filename_t(XDR *, filename_t*);
#elif __STDC__
extern  bool_t xdr_filename_t(XDR *, filename_t*);
#else /* Old Style C */
bool_t xdr_filename_t();
#endif /* Old Style C */


struct readdir_args {
	char *dirname;
};
typedef struct readdir_args readdir_args;
#ifdef __cplusplus
extern "C" bool_t xdr_readdir_args(XDR *, readdir_args*);
#elif __STDC__
extern  bool_t xdr_readdir_args(XDR *, readdir_args*);
#else /* Old Style C */
bool_t xdr_readdir_args();
#endif /* Old Style C */


struct readdir_result {
	struct {
		u_int filenames_len;
		filename_t *filenames_val;
	} filenames;
};
typedef struct readdir_result readdir_result;
#ifdef __cplusplus
extern "C" bool_t xdr_readdir_result(XDR *, readdir_result*);
#elif __STDC__
extern  bool_t xdr_readdir_result(XDR *, readdir_result*);
#else /* Old Style C */
bool_t xdr_readdir_result();
#endif /* Old Style C */


#define NFS_PROGRAM ((rpc_uint)0x21000001)
#define NFS_VERSION_1 ((rpc_uint)1)

#ifdef __cplusplus
#define ls ((rpc_uint)1)
extern "C" char ** ls_1(char **, CLIENT *);
extern "C" char ** ls_1_svc(char **, struct svc_req *);
#define create ((rpc_uint)2)
extern "C" int * create_1(char **, CLIENT *);
extern "C" int * create_1_svc(char **, struct svc_req *);
#define delete ((rpc_uint)3)
extern "C" int * delete_1(char **, CLIENT *);
extern "C" int * delete_1_svc(char **, struct svc_req *);
#define retrieve_file ((rpc_uint)4)
extern "C" chunk * retrieve_file_1(request *, CLIENT *);
extern "C" chunk * retrieve_file_1_svc(request *, struct svc_req *);
#define send_file ((rpc_uint)5)
extern "C" int * send_file_1(chunk *, CLIENT *);
extern "C" int * send_file_1_svc(chunk *, struct svc_req *);
#define mynfs_mkdir ((rpc_uint)6)
extern "C" int * mynfs_mkdir_1(char **, CLIENT *);
extern "C" int * mynfs_mkdir_1_svc(char **, struct svc_req *);
#define mynfs_remdir ((rpc_uint)7)
extern "C" int * mynfs_remdir_1(char **, CLIENT *);
extern "C" int * mynfs_remdir_1_svc(char **, struct svc_req *);
#define mynfs_read ((rpc_uint)8)
extern "C" chunk * mynfs_read_1(request *, CLIENT *);
extern "C" chunk * mynfs_read_1_svc(request *, struct svc_req *);
#define mynfs_write ((rpc_uint)9)
extern "C" int * mynfs_write_1(chunk *, CLIENT *);
extern "C" int * mynfs_write_1_svc(chunk *, struct svc_req *);
#define mynfs_readdir ((rpc_uint)10)
extern "C" readdir_result * mynfs_readdir_1(readdir_args *, CLIENT *);
extern "C" readdir_result * mynfs_readdir_1_svc(readdir_args *, struct svc_req *);

#elif __STDC__
#define ls ((rpc_uint)1)
extern  char ** ls_1(char **, CLIENT *);
extern  char ** ls_1_svc(char **, struct svc_req *);
#define create ((rpc_uint)2)
extern  int * create_1(char **, CLIENT *);
extern  int * create_1_svc(char **, struct svc_req *);
#define delete ((rpc_uint)3)
extern  int * delete_1(char **, CLIENT *);
extern  int * delete_1_svc(char **, struct svc_req *);
#define retrieve_file ((rpc_uint)4)
extern  chunk * retrieve_file_1(request *, CLIENT *);
extern  chunk * retrieve_file_1_svc(request *, struct svc_req *);
#define send_file ((rpc_uint)5)
extern  int * send_file_1(chunk *, CLIENT *);
extern  int * send_file_1_svc(chunk *, struct svc_req *);
#define mynfs_mkdir ((rpc_uint)6)
extern  int * mynfs_mkdir_1(char **, CLIENT *);
extern  int * mynfs_mkdir_1_svc(char **, struct svc_req *);
#define mynfs_remdir ((rpc_uint)7)
extern  int * mynfs_remdir_1(char **, CLIENT *);
extern  int * mynfs_remdir_1_svc(char **, struct svc_req *);
#define mynfs_read ((rpc_uint)8)
extern  chunk * mynfs_read_1(request *, CLIENT *);
extern  chunk * mynfs_read_1_svc(request *, struct svc_req *);
#define mynfs_write ((rpc_uint)9)
extern  int * mynfs_write_1(chunk *, CLIENT *);
extern  int * mynfs_write_1_svc(chunk *, struct svc_req *);
#define mynfs_readdir ((rpc_uint)10)
extern  readdir_result * mynfs_readdir_1(readdir_args *, CLIENT *);
extern  readdir_result * mynfs_readdir_1_svc(readdir_args *, struct svc_req *);

#else /* Old Style C */
#define ls ((rpc_uint)1)
extern  char ** ls_1();
extern  char ** ls_1_svc();
#define create ((rpc_uint)2)
extern  int * create_1();
extern  int * create_1_svc();
#define delete ((rpc_uint)3)
extern  int * delete_1();
extern  int * delete_1_svc();
#define retrieve_file ((rpc_uint)4)
extern  chunk * retrieve_file_1();
extern  chunk * retrieve_file_1_svc();
#define send_file ((rpc_uint)5)
extern  int * send_file_1();
extern  int * send_file_1_svc();
#define mynfs_mkdir ((rpc_uint)6)
extern  int * mynfs_mkdir_1();
extern  int * mynfs_mkdir_1_svc();
#define mynfs_remdir ((rpc_uint)7)
extern  int * mynfs_remdir_1();
extern  int * mynfs_remdir_1_svc();
#define mynfs_read ((rpc_uint)8)
extern  chunk * mynfs_read_1();
extern  chunk * mynfs_read_1_svc();
#define mynfs_write ((rpc_uint)9)
extern  int * mynfs_write_1();
extern  int * mynfs_write_1_svc();
#define mynfs_readdir ((rpc_uint)10)
extern  readdir_result * mynfs_readdir_1();
extern  readdir_result * mynfs_readdir_1_svc();
#endif /* Old Style C */

#endif /* !_NFS_H_RPCGEN */
