/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LUNGIME_FILENAME 150
#define LUNGIME_FILEDATA 1024

struct cerere {
	char *numeFisier;
	int startOffset;
};
typedef struct cerere cerere;

struct chunk {
	char *fisier;
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int dim;
	int destOffset;
};
typedef struct chunk chunk;

#define MYNFS_RPC 0x21000001
#define MYNFS_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define MYNFS_OPEN 1
extern  int * mynfs_open_1(char **, CLIENT *);
extern  int * mynfs_open_1_svc(char **, struct svc_req *);
#define MYNFS_CLOSE 2
extern  int * mynfs_close_1(int *, CLIENT *);
extern  int * mynfs_close_1_svc(int *, struct svc_req *);
#define MYNFS_READ 3
extern  int * mynfs_read_1(int *, CLIENT *);
extern  int * mynfs_read_1_svc(int *, struct svc_req *);
#define MYNFS_WRITE 4
extern  int * mynfs_write_1(int *, CLIENT *);
extern  int * mynfs_write_1_svc(int *, struct svc_req *);
#define MYNFS_TOUCH 5
extern  int * mynfs_touch_1(char **, CLIENT *);
extern  int * mynfs_touch_1_svc(char **, struct svc_req *);
#define MYNFS_RM 6
extern  int * mynfs_rm_1(char **, CLIENT *);
extern  int * mynfs_rm_1_svc(char **, struct svc_req *);
#define MYNFS_LS 7
extern  char ** mynfs_ls_1(char **, CLIENT *);
extern  char ** mynfs_ls_1_svc(char **, struct svc_req *);
#define MYNFS_MKDIR 8
extern  int * mynfs_mkdir_1(char **, CLIENT *);
extern  int * mynfs_mkdir_1_svc(char **, struct svc_req *);
#define MYNFS_RMDIR 9
extern  int * mynfs_rmdir_1(char **, CLIENT *);
extern  int * mynfs_rmdir_1_svc(char **, struct svc_req *);
#define MYNFS_OPENDIR 10
extern  int * mynfs_opendir_1(char **, CLIENT *);
extern  int * mynfs_opendir_1_svc(char **, struct svc_req *);
#define MYNFS_READDIR 11
extern  int * mynfs_readdir_1(int *, CLIENT *);
extern  int * mynfs_readdir_1_svc(int *, struct svc_req *);
#define MYNFS_GETCHUNK 12
extern  chunk * mynfs_getchunk_1(cerere *, CLIENT *);
extern  chunk * mynfs_getchunk_1_svc(cerere *, struct svc_req *);
extern int mynfs_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MYNFS_OPEN 1
extern  int * mynfs_open_1();
extern  int * mynfs_open_1_svc();
#define MYNFS_CLOSE 2
extern  int * mynfs_close_1();
extern  int * mynfs_close_1_svc();
#define MYNFS_READ 3
extern  int * mynfs_read_1();
extern  int * mynfs_read_1_svc();
#define MYNFS_WRITE 4
extern  int * mynfs_write_1();
extern  int * mynfs_write_1_svc();
#define MYNFS_TOUCH 5
extern  int * mynfs_touch_1();
extern  int * mynfs_touch_1_svc();
#define MYNFS_RM 6
extern  int * mynfs_rm_1();
extern  int * mynfs_rm_1_svc();
#define MYNFS_LS 7
extern  char ** mynfs_ls_1();
extern  char ** mynfs_ls_1_svc();
#define MYNFS_MKDIR 8
extern  int * mynfs_mkdir_1();
extern  int * mynfs_mkdir_1_svc();
#define MYNFS_RMDIR 9
extern  int * mynfs_rmdir_1();
extern  int * mynfs_rmdir_1_svc();
#define MYNFS_OPENDIR 10
extern  int * mynfs_opendir_1();
extern  int * mynfs_opendir_1_svc();
#define MYNFS_READDIR 11
extern  int * mynfs_readdir_1();
extern  int * mynfs_readdir_1_svc();
#define MYNFS_GETCHUNK 12
extern  chunk * mynfs_getchunk_1();
extern  chunk * mynfs_getchunk_1_svc();
extern int mynfs_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cerere (XDR *, cerere*);
extern  bool_t xdr_chunk (XDR *, chunk*);

#else /* K&R C */
extern bool_t xdr_cerere ();
extern bool_t xdr_chunk ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
