//
// Created by Alexandra Zamfirescu on 15.01.2024.
//

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

// FISIERUL PENTRU SERVER

#include "nfs.h"

char **
ls_1_svc(char **argp, struct svc_req *rqstp)
{
    static char * result;

    /*
     * insert server code here
     */

    return &result;
}

int *
create_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
delete_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

chunk *
retrieve_file_1_svc(request *argp, struct svc_req *rqstp)
{
    static chunk  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
send_file_1_svc(chunk *argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
mkdir_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;
    const char *dirname = *argp;

    result = mkdir(dirname, 0777); // 0777 = permisiuni read, write, execute pentru user, group si restul

    return &result;
}

int *
open_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
close_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

chunk *
read_1_svc(request *argp, struct svc_req *rqstp)
{
    static chunk  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
write_1_svc(chunk *argp, struct svc_req *rqstp)
{
    static int  result;

    /*
     * insert server code here
     */

    return &result;
}

int *
opendir_1_svc(opendir_args *argp, struct svc_req *rqstp)
{
    static int  result;
    DIR *dir = opendir(argp->dirname);

    if (dir != NULL) {
        result = 0;
        closedir(dir);
    } else {
        result = -1;
    }

    return &result;
}

readdir_result *
readdir_1_svc(readdir_args *argp, struct svc_req *rqstp)
{
    static readdir_result  result;
    DIR *dir;
    struct dirent *entry;

    dir = opendir(argp->dirname);
    if (dir == NULL) {
        result.more = false;
        return &result;
    }

    result.filenames[0] = '\0';
    while ((entry = readdir(dir)) != NULL) {
        strcat(result.filenames, entry->d_name);
        strcat(result.filenames, "\n");
    }

    closedir(dir);
    result.more = false;

    return &result;
}