/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_cerere (XDR *xdrs, cerere *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->numeFisier, LUNGIME_FILENAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->startOffset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chunk (XDR *xdrs, chunk *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fisier, LUNGIME_FILENAME))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, LUNGIME_FILEDATA))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dim))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->destOffset))
		 return FALSE;
	return TRUE;
}
