/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
mynfs_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *mynfs_open_1_arg;
		int mynfs_close_1_arg;
		int mynfs_read_1_arg;
		int mynfs_write_1_arg;
		char *mynfs_touch_1_arg;
		char *mynfs_rm_1_arg;
		char *mynfs_ls_1_arg;
		char *mynfs_mkdir_1_arg;
		char *mynfs_rmdir_1_arg;
		char *mynfs_opendir_1_arg;
		int mynfs_readdir_1_arg;
		cerere mynfs_getchunk_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MYNFS_OPEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_open_1_svc;
		break;

	case MYNFS_CLOSE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_close_1_svc;
		break;

	case MYNFS_READ:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_read_1_svc;
		break;

	case MYNFS_WRITE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_write_1_svc;
		break;

	case MYNFS_TOUCH:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_touch_1_svc;
		break;

	case MYNFS_RM:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_rm_1_svc;
		break;

	case MYNFS_LS:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) mynfs_ls_1_svc;
		break;

	case MYNFS_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_mkdir_1_svc;
		break;

	case MYNFS_RMDIR:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_rmdir_1_svc;
		break;

	case MYNFS_OPENDIR:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_opendir_1_svc;
		break;

	case MYNFS_READDIR:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mynfs_readdir_1_svc;
		break;

	case MYNFS_GETCHUNK:
		_xdr_argument = (xdrproc_t) xdr_cerere;
		_xdr_result = (xdrproc_t) xdr_chunk;
		local = (char *(*)(char *, struct svc_req *)) mynfs_getchunk_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MYNFS_RPC, MYNFS_VERSION_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MYNFS_RPC, MYNFS_VERSION_1, mynfs_rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MYNFS_RPC, MYNFS_VERSION_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MYNFS_RPC, MYNFS_VERSION_1, mynfs_rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MYNFS_RPC, MYNFS_VERSION_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
